x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "100m"
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  cf-ddns:
    image: qmcgaw/ddns-updater:${DDNS_TAG:-v2}
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      CONFIG: >-
        {"settings": [
        {"provider": "cloudflare", "zone_identifier": "${CF_ZONE_ID}",
        "domain": "${RPC_HOST}.${DOMAIN}", "ttl": 1, "token": "${CF_DNS_API_TOKEN}",
        "proxied": ${DDNS_PROXY:-false}, "ip_version": "ipv4"},
        {"provider": "cloudflare", "zone_identifier": "${CF_ZONE_ID}",
        "domain": "${WS_HOST}.${DOMAIN}", "ttl": 1, "token": "${CF_DNS_API_TOKEN}",
        "proxied": ${DDNS_PROXY:-false}, "ip_version": "ipv4"}
        ]}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
